server:
  port: 10010
spring:
   application:
     name: zouul-server
eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:10086/eureka
zuul:
     routes:
       user-server:
          path: /hello/**
          serviceId: user-server
          #自动识别前缀
          strip-prefix: false
        #忽略某个服务
     ignored-services:
          - consumer-server
hystrix:
   command:
     default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
   ConnectionTimeout: 500 # 连接超时时间(ms)
   ReadTimeout: 2000 # 通信超时时间(ms)

