
server:
  port: 8081
  tomcat:   #tomcat 线程数，编码格式  设置
       uri-encoding: UTF-8
       max-threads: 1000
       max-connections: 20000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
     type-aliases-package: cn.itcast.user.pojo
